import Head from "next/head"

//pages
import HelpWebsite from "./help-website/index"

export default function Home() {
  return (
    <>
      <Head>
        <title>Help Praxu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HelpWebsite />
      </main>
    </>
  )
}
